services:
 nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Asia/Kolkata
    volumes:
      - ${PATH_CONFIG}:/config
      - ${PATH_DATA}:/data
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    external: true
    name: homelab

