services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    env_file: .env
    volumes:
      - ./config:/app/config
    environment:
       PUID: $PUID
       PGID: $PGID
       HOMEPAGE_ALLOWED_HOSTS: $HOMEPAGE_ALLOWED_HOSTS
    networks:
      - homelab
    restart: unless-stopped

networks:
  homelab:
    external: true
    name: homelab
