services:
  portainer:
    image: portainer/portainer-ce:2.29.0-alpine
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PORTAINER_DATA_PATH:/data
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    external: true
    name: homelab
