services:
  portainer:
    image: portainer/portainer-ce:2.29.0-alpine
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - ./portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  portainer_data: