---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - Github:
        - abbr: GH
          href: "{{HOMEPAGE_VAR_GITHUB_URL}}"

- Social:
    - X:
        - abbr: X
          href: "{{HOMEPAGE_VAR_X_URL}}"

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
