---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Homelab:
    - NextCloud:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/nextcloud.png
        href: "{{HOMEPAGE_VAR_NEXTCLOUD_URL}}"
        description: storage
