---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Homelab:
    - NextCloud:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/nextcloud.png
        href: "{{HOMEPAGE_VAR_NEXTCLOUD_URL}}"
        description: storage
- Tools:
    - DuckDNS:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/duckdns.png
        href: "{{HOMEPAGE_VAR_DUCKDNS_URL}}"
        description: dynamic dns
    - Taiscale:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/tailscale-light.png
        href: "{{HOMEPAGE_VAR_TAILSCALE_URL}}"
        description: VPN

- SelfHosted:
    - Test1:
        description: test