# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

theme: dark
color: zinc


providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey