services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - $KUMA_DATA_PATH:/app/data
    networks:
      - homelab
    restart: unless-stopped

networks:
  homelab:
    external: true
    name: homelab
