services:
  NPM:
    image: 'jc21/nginx-proxy-manager:2.12.3'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '127.0.0.1:80:80'
      - '81:81'
      - '127.0.0.1:443:443'
    volumes:
      - $NPM_DATA_PATH:/data
      - $NPM_CERTS_PATH:/etc/letsencrypt
    networks:
      - homelab
    dns:
      - 8.8.8.8
      - 1.1.1.1

networks:
  homelab:
    external: true
    name: homelab
