services:
  NPM:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '127.0.0.1:80:80'
      - '127.0.0.1:81:81'
      - '127.0.0.1:443:443'
    volumes:
      - /mnt/storage/nginx_proxy_manager/data:/data
      - /mnt/storage/nginx_proxy_manager/letsencrypt:/etc/letsencrypt
    networks:
      - homelab
    dns:
      - 8.8.8.8
      - 1.1.1.1

networks:
  homelab:
    external: true
    name: homelab
